# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.opencode
default-branch: stable
runtime: io.github.kardbord.Platform
runtime-version: stable
sdk: io.github.kardbord.Sdk
build-extension: true
separate-locales: false

modules:
  - name: opencode
    buildsystem: simple
    build-commands:
      - install -Dm755 opencode ${FLATPAK_DEST}/bin/opencode
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-linux-x64.tar.gz
        sha256: 0cddc222418b8553669905a8980c0cda7088f00da24d83d6ac76b01c9fdb2aaf
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-x64\\.tar\\.gz$")) | .browser_download_url'
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-linux-arm64.tar.gz
        sha256: dcb1b5ec5687b43f87749560021f9203f3809e0ce5ae44ff9be8ae17083fe4ba
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-arm64\\.tar\\.gz$")) | .browser_download_url'
