# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.opencode
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: opencode
    buildsystem: simple
    build-commands:
      - install -Dm755 opencode ${FLATPAK_DEST}/bin/opencode
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.29/opencode-linux-x64.tar.gz
        sha256: ea800b7ff56226b70952126c9fc1e2517ca4c4b5682fd9d3f9e87449697a1194
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-x64\\.tar\\.gz$")) | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.29/opencode-linux-arm64.tar.gz
        sha256: 70baf769395ca4e7a68924026530c390eace194f3b7e4919d4efcb2aa2eed3c0
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-arm64\\.tar\\.gz$")) |
            .browser_download_url
