# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.opencode
default-branch: stable
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
build-extension: true
separate-locales: false

modules:
  - name: opencode
    buildsystem: simple
    build-commands:
      - install -Dm755 opencode ${FLATPAK_DEST}/bin/opencode
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.21/opencode-linux-x64.tar.gz
        sha256: d910c3ed7613bb5791a328904615d41cc25b7d3a6b470e3199ab0426a995b38a
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-x64\\.tar\\.gz$")) | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/anomalyco/opencode/releases/download/v1.18.21/opencode-linux-arm64.tar.gz
        sha256: d30d2cba74617f4e7b96e25563c9572ffe453f9eae70fc0df16286813537ee72
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/anomalyco/opencode/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-arm64\\.tar\\.gz$")) |
            .browser_download_url
