# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.treesitter-cli
default-branch: stable
runtime: io.github.kardbord.Sdk
runtime-version: stable
sdk: io.github.kardbord.Sdk
command: treesitter-cli-wrapper

add-extensions:
  io.github.kardbord.tool.treesitter-cli:
    directory: lib/kardbord-tools/treesitter-cli
    version: stable
    no-autodownload: false

modules:
  - name: treesitter-cli
    buildsystem: simple
    build-commands:
      - install -Dm755 treesitter-cli-wrapper /app/bin/treesitter-cli-wrapper
    sources:
      - type: file
        path: treesitter-cli-wrapper

cleanup-commands:
  - mkdir -p ${FLATPAK_DEST}/lib/kardbord-tools/treesitter-cli
