# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json
id: io.github.kardbord.tool.golangci-lint
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false
modules:
  - name: golangci-lint
    buildsystem: simple
    build-commands:
      - install -Dm755 golangci-lint ${FLATPAK_DEST}/bin/golangci-lint
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/golangci/golangci-lint/releases/download/v2.14.0/golangci-lint-2.14.0-linux-amd64.tar.gz
        sha256: ab90aeb7b066f92a33415b638a50fe5344bbb75a0d32ad30cc248d88f81032ab
        x-checker-data:
          type: json
          url: https://api.github.com/repos/golangci/golangci-lint/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("-linux-amd64\\.tar\\.gz$"))
            | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/golangci/golangci-lint/releases/download/v2.14.0/golangci-lint-2.14.0-linux-arm64.tar.gz
        sha256: ee7ec5f3453d15ddf106fae5a4d6c71737712348a979d1fe9cd52ec7ea299bae
        x-checker-data:
          type: json
          url: https://api.github.com/repos/golangci/golangci-lint/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("-linux-arm64\\.tar\\.gz$"))
            | .browser_download_url
