# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.yq
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: yq
    buildsystem: simple
    build-commands:
      - install -Dm755 yq_* ${FLATPAK_DEST}/bin/yq
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/mikefarah/yq/releases/download/v4.54.1/yq_linux_amd64.tar.gz
        sha256: e68a456f90c577af3fe4960184b3a3cf5c461e0348407c10f107da3a5fec8972
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/mikefarah/yq/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("yq_linux_amd64\\.tar\\.gz$"))
            | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/mikefarah/yq/releases/download/v4.54.1/yq_linux_arm64.tar.gz
        sha256: 8c27f6e7476fb5acefb9352e3d30f6bc2dc93f1956eb92e8da727173fb7ec6d3
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/mikefarah/yq/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("yq_linux_arm64\\.tar\\.gz$"))
            | .browser_download_url
