# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.uv
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: uv
    buildsystem: simple
    build-commands:
      - install -Dm755 uv ${FLATPAK_DEST}/bin/uv
      - install -Dm755 uvx ${FLATPAK_DEST}/bin/uvx
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/astral-sh/uv/releases/download/0.12.7/uv-x86_64-unknown-linux-gnu.tar.gz
        sha256: 788f18abea7c5f55d6216e4f5613fd89d4d59b631efeec117b2b07fe72f1da21
        x-checker-data:
          type: json
          url: https://api.github.com/repos/astral-sh/uv/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("x86_64-unknown-linux-gnu\\.tar\\.gz$"))
            | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/astral-sh/uv/releases/download/0.12.7/uv-aarch64-unknown-linux-gnu.tar.gz
        sha256: 66393193038dd7eb108abd7a218d9cec04ac70ab98242b0720fa94de19223b7c
        x-checker-data:
          type: json
          url: https://api.github.com/repos/astral-sh/uv/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("aarch64-unknown-linux-gnu\\.tar\\.gz$"))
            | .browser_download_url
