# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.uv
default-branch: stable
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
build-extension: true
separate-locales: false

modules:
  - name: uv
    buildsystem: simple
    build-commands:
      - install -Dm755 uv ${FLATPAK_DEST}/bin/uv
      - install -Dm755 uvx ${FLATPAK_DEST}/bin/uvx
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/astral-sh/uv/releases/download/0.12.5/uv-x86_64-unknown-linux-gnu.tar.gz
        sha256: 68a509da24b06b4223a1c0175fb5eb5bc79342b76cbeff0cfe51ac3f5b17b6b2
        x-checker-data:
          type: json
          url: https://api.github.com/repos/astral-sh/uv/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("x86_64-unknown-linux-gnu\\.tar\\.gz$")) | .browser_download_url'
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/astral-sh/uv/releases/download/0.12.5/uv-aarch64-unknown-linux-gnu.tar.gz
        sha256: 9bf43b4d1a07665bf64d4c4e710930b382321a785e0eb10aac07f46471f86a31
        x-checker-data:
          type: json
          url: https://api.github.com/repos/astral-sh/uv/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("aarch64-unknown-linux-gnu\\.tar\\.gz$")) | .browser_download_url'
