# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.treesitter-cli
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: treesitter-cli
    buildsystem: simple
    build-commands:
      - unzip *.zip
      - install -Dm755 tree-sitter ${FLATPAK_DEST}/bin/tree-sitter
    sources:
      - type: file
        only-arches:
          - x86_64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.27.0/tree-sitter-cli-linux-x64.zip
        sha256: e4a3826bcd0fe099ee3a5617767374939cbc23c4a35b5b53f5fc04142525a2c1
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-x64\\.zip$")) | .browser_download_url
      - type: file
        only-arches:
          - aarch64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.27.0/tree-sitter-cli-linux-arm64.zip
        sha256: 6260b621bf5ab87027dfb463bf955504ef32cdcda62b81f28447753e48c83a62
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("linux-arm64\\.zip$")) | .browser_download_url
