# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.treesitter-cli
default-branch: stable
runtime: io.github.kardbord.Platform
runtime-version: stable
sdk: io.github.kardbord.Sdk
build-extension: true
separate-locales: false

modules:
  - name: treesitter-cli
    buildsystem: simple
    build-commands:
      - install -Dm755 tree-sitter ${FLATPAK_DEST}/bin/tree-sitter
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.12/tree-sitter-cli-linux-x64.zip
        sha256: c33ace12fa7a94d09c97054da621bf7a6a3159f765b1839a898232de283d641d
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-x64\\.zip$")) | .browser_download_url'
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.12/tree-sitter-cli-linux-arm64.zip
        sha256: be970bfad7b557ffc62b1a7b4c92341a9c6e16d619e9880e43f07c4a4e6eb52a
        strip-components: 0
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-arm64\\.zip$")) | .browser_download_url'
