# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.treesitter-cli
default-branch: stable
runtime: io.github.kardbord.Platform
runtime-version: stable
sdk: io.github.kardbord.Sdk
build-extension: true
separate-locales: false

modules:
  - name: treesitter-cli
    buildsystem: simple
    build-commands:
      - gunzip *.gz
      - mv tree-sitter* tree-sitter
      - install -Dm755 tree-sitter ${FLATPAK_DEST}/bin/tree-sitter
    sources:
      - type: file
        only-arches:
          - x86_64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.12/tree-sitter-linux-x64.gz
        sha256: d00ac0daefc4bf8c4b57842a5c0509927232faad1d83157b64fbad4e2e8d9a8b
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-x64\\.zip$")) | .browser_download_url'
      - type: file
        only-arches:
          - aarch64
        url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.12/tree-sitter-linux-arm64.gz
        sha256: cfbf3d9aad8e326878ab1846885a9c2b782a0333273591616f34bf556d525586
        x-checker-data:
          type: json
          url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
          version-query: '.tag_name | sub("^v"; "")'
          url-query: '.assets[] | select(.name | test("linux-arm64\\.zip$")) | .browser_download_url'
