# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.viu
default-branch: stable
runtime: io.github.kardbord.Platform
runtime-version: stable
sdk: io.github.kardbord.Sdk
command: viu-wrapper

add-extensions:
  io.github.kardbord.tool.viu:
    directory: lib/kardbord-tools/viu
    version: stable
    no-autodownload: false

modules:
  - name: viu
    buildsystem: simple
    build-commands:
      - install -Dm755 viu-wrapper /app/bin/viu-wrapper
    sources:
      - type: file
        path: viu-wrapper

cleanup-commands:
  - mkdir -p ${FLATPAK_DEST}/lib/kardbord-tools/viu
