# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.sk
default-branch: stable
runtime: io.github.kardbord.Platform
runtime-version: stable
sdk: io.github.kardbord.Sdk
command: sk-wrapper

add-extensions:
  io.github.kardbord.tool.sk:
    directory: lib/kardbord-tools/sk
    version: stable
    no-autodownload: false

modules:
  - name: sk
    buildsystem: simple
    build-commands:
      - install -Dm755 sk-wrapper /app/bin/sk-wrapper
    sources:
      - type: file
        path: sk-wrapper

cleanup-commands:
  - mkdir -p ${FLATPAK_DEST}/lib/kardbord-tools/sk
  - mkdir -p ${FLATPAK_DEST}/lib/sdk
