# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.dev
default-branch: stable
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
command: kardbord-dev

add-extensions:
  io.github.kardbord.tool:
    directory: lib/kardbord-tools
    subdirectories: true
    no-autodownload: true
    version: stable
    add-ld-path: lib

modules:
  - name: kardbord-env
    buildsystem: simple
    build-commands:
      - install -Dm755 activate-kardbord-env /app/bin/activate-kardbord-env
      - install -Dm755 kardbord-dev /app/bin/kardbord-dev
      - install -d /app/lib/kardbord-tools
    sources:
      - type: file
        path: activate-kardbord-env
      - type: file
        path: kardbord-dev