# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.dev
default-branch: stable
runtime: org.freedesktop.Sdk
runtime-version: '25.08'
sdk: org.freedesktop.Sdk//25.08
command: activate-kardbord-env

add-extensions:
  io.github.kardbord.tool:
    directory: lib/kardbord-tools
    subdirectories: true
    no-autodownload: false
    version: stable
    add-ld-path: lib

inherit-extensions:
  - org.freedesktop.Sdk.Extension

inherit-sdk-extensions:
  - org.freedesktop.Sdk.Extension

modules:
  - name: kardbord-env
    buildsystem: simple
    build-commands:
      - install -Dm755 activate-kardbord-env /app/bin/activate-kardbord-env
      - install -d /app/lib/kardbord-tools
      - install -d /app/lib/sdk
    sources:
      - type: file
        path: activate-kardbord-env
