# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.sk
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: sk
    buildsystem: simple
    build-commands:
      - install -Dm755 sk ${FLATPAK_DEST}/bin/sk
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/skim-rs/skim/releases/download/v5.6.6/skim-x86_64-unknown-linux-musl.tar.xz
        sha256: 858e59f72c16fbe32b95987b90e31a14df1c592b4ca1a88821f0e044c9b5602d
        x-checker-data:
          type: json
          url: https://api.github.com/repos/skim-rs/skim/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("x86_64-unknown-linux-musl\\.tar\\.xz$"))
            | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/skim-rs/skim/releases/download/v5.6.6/skim-aarch64-unknown-linux-musl.tar.xz
        sha256: 508173e4eda04a65facf5e268070509604a0bf983071e8c578118172b4b1bf56
        x-checker-data:
          type: json
          url: https://api.github.com/repos/skim-rs/skim/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("aarch64-unknown-linux-musl\\.tar\\.xz$"))
            | .browser_download_url
