# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.sk
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: sk
    buildsystem: simple
    build-commands:
      - install -Dm755 sk ${FLATPAK_DEST}/bin/sk
    sources:
      - type: archive
        only-arches:
          - x86_64
        url: https://github.com/skim-rs/skim/releases/download/v5.7.0/skim-x86_64-unknown-linux-musl.tar.xz
        sha256: 73df0c2d65697a82bc1b1670f1b1858bf60f1d8d70976fcc38e660c560de1a00
        x-checker-data:
          type: json
          url: https://api.github.com/repos/skim-rs/skim/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("x86_64-unknown-linux-musl\\.tar\\.xz$"))
            | .browser_download_url
      - type: archive
        only-arches:
          - aarch64
        url: https://github.com/skim-rs/skim/releases/download/v5.7.0/skim-aarch64-unknown-linux-musl.tar.xz
        sha256: 2968effb1600cefc84a671a90e5ee42da40cf32e785d93b7a9c6b7a69d288b9f
        x-checker-data:
          type: json
          url: https://api.github.com/repos/skim-rs/skim/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name | test("aarch64-unknown-linux-musl\\.tar\\.xz$"))
            | .browser_download_url
