# yaml-language-server: $schema=https://www.schemastore.org/flatpak-manifest.json

id: io.github.kardbord.tool.git
default-branch: stable
runtime: io.github.kardbord.dev
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
separate-locales: false

modules:
  - name: git
    buildsystem: simple
    build-commands:
      - make NO_RUST=1 NO_TCLTK=1 CFLAGS="-O2 -s" prefix=${FLATPAK_DEST} -j ${FLATPAK_BUILDER_N_JOBS}
        all install
    sources:
      - type: archive
        url: https://github.com/git/git/archive/refs/tags/v2.56.0-rc1.tar.gz
        sha256: 2914082cd7e7e495742f57a54dbdf4021b8455c2e77a3f8eb010c7d3eac829bf
        x-checker-data:
          type: json
          url: https://api.github.com/repos/git/git/tags
          version-query: .[0].name
          url-query: '"https://github.com/git/git/archive/refs/tags/\(.[0].name).tar.gz"'
