# Dummy flatpak manifest for FEDC to check for upstream updates.
id: kardbord-breakout
modules:
  - name: kardbord-breakout
    sources:
      - type: git
        url: https://github.com/Kardbord/breakout.git
        tag: v1.0.7
        commit: 24810e2c5eacb23ab96dd9fbde8dfd6ac17a9cb0
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$
